langchain4j:
  community:
    dashscope:
      # LLM
      chat-model:
        api-key: ${DASHSCOPE_API_KEY}
        model-name: qwen3-max
        temperature: 0.7
      # Streaming LLM
      streaming-chat-model:
        api-key: ${DASHSCOPE_API_KEY}
        model-name: qwen3-max
        temperature: 0.7
      # Embedding model
      embedding-model:
        api-key: ${DASHSCOPE_API_KEY}
        model-name: text-embedding-v3
        dimensions: 1024

# Embedding model - PgVector
pgvector:
  host: ${PGVECTOR_HOST}
  port: ${PGVECTOR_PORT}
  database: ${PGVECTOR_DATABASE}
  user: ${PGVECTOR_USER}
  password: ${PGVECTOR_PASSWORD}
  table: ${PGVECTOR_TABLE}

# chat config
chat:
  compress:
    enabled: true
    maxTotalTokens: 6000
    recentRawCount: 10
    minMessagesToCompress: 20

mcp:
  search-link: ${SEARCH_MCP_LINK}